- k8s_v1_persistent_volume_claim:
    name: '{{ mysql_claim_name }}'
    namespace: '{{ namespace }}'
    state: absent

- openshift_v1_deployment_config:
    name: mysql
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service:
    name: '{{ mysql_service_name }}'
    namespace: '{{ namespace }}'
    state: absent    

- openshift_v1_deployment_config:
    name: ups
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service:
    name: '{{ ups_service_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service:
    name: '{{ ups_proxy_service_name }}'
    namespace: '{{ namespace }}'
    state: absent  

- openshift_v1_route:
    name: '{{ ups_route_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_secret:
    name: '{{ ups_secret_name }}'
    namespace: '{{ namespace }}'
    state: absent

- k8s_v1_service_account:
    name: '{{ proxy_serviceaccount_name }}'
    namespace: '{{ namespace }}'
    state: absent

- name: "Delete variant bindings"
  shell:  oc delete secrets -l secretType==mobile-client-binding-secret -n '{{ namespace }}'