---
- name: Test unifiedpush-apb
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - /opt/ansible/vars/main.yml
  - /opt/ansible/vars/test.yml

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  post_tasks:
  - name: create project for namespace
    openshift_v1_project:
      name: '{{ namespace }}'
  - name: Run the provision role
    include_role: name=provision-unifiedpush-apb
  - name: Test provision role
    include_role: name=test-unifiedpush-apb tasks_from=provision.yml
  - name: Run the bind role
    include_role: name=bind-unifiedpush-apb
  - name: Test bind role
    include_role: name=test-unifiedpush-apb tasks_from=bind.yml
  - name: Run the unbind role
    include_role: name=unbind-unifiedpush-apb
  - name: Test unbind role
    include_role: name=test-unifiedpush-apb tasks_from=unbind.yml
  - name: Run the deprovision role
    include_role: name=deprovision-unifiedpush-apb
  - name: Test deprovision role
    include_role: name=test-unifiedpush-apb tasks_from=deprovision.yml